### PR TITLE
Use Node process.platform property to determine the platform

### PR DESCRIPTION
**Pull request by basst85**
Fixes this bug:
https://github.com/NativePHP/laravel/issues/96

### CODE REVIEW

**Comment by mpociot** [comment]
Unfortunately we can not fix it like this, as this would loose cross compilation abilities. 

For example, you could create a Linux binary from windows. 
Or a Windows binary on a Mac. 

That's why we have to pass the OS as an argument instead. 

I think the correct way to fix this would be in the "InstallCommand" and then pass the correct OS flag, as determined by PHP.

**Comment by basst85** [comment]
> Unfortunately we can not fix it like this, as this would loose cross compilation abilities.
> 
> For example, you could create a Linux binary from windows. Or a Windows binary on a Mac.
> 
> That's why we have to pass the OS as an argument instead.
> 
> I think the correct way to fix this would be in the "InstallCommand" and then pass the correct OS flag, as determined by PHP.

You're right.

Agree. 
At this moment the OS argument (--win / --linux)  is not passed (correctly) when running npm install from "DevelopCommand", so it thinks you're running mac in stead of windows or linux.

**Comment by chrisreedio** [comment]
@basst85 
Check out my open PR [here](https://github.com/chrisreedio/electron/pull/5).

I believe it should handle this gracefully.

I'm running Windows (and WSL, not that it matters for this topic) and natively in Windows (via powershell in VSCode) the develop command now opens the App without problems. 

Still working on issues with the build command not outputting files but that will most likely be a separate PR.

**Comment by basst85** [comment]
> @basst85 Check out my open PR [here](https://github.com/chrisreedio/electron/pull/5).
> 
> I believe it should handle this gracefully.
> 
> I'm running Windows (and WSL, not that it matters for this topic) and natively in Windows (via powershell in VSCode) the develop command now opens the App without problems.
> 
> Still working on issues with the build command not outputting files but that will most likely be a separate PR.

Thanks! Missed that PR. 
I will close this PR because it's a duplicate fix :-)

**Pull request closed without merging**
