### PR TITLE
Fix php path in queue command

### PR DESCRIPTION
**Pull request by phuclh**
Fix php path in queue command. It is pointing to the directory, not the php binary

### CODE REVIEW

**Comment by mpociot** [comment]
Mh...you're probably coming from Windows?
But in any case, there should be a file called `php` in that directory.

**Comment by phuclh** [comment]
@mpociot no, I am using Mac. When I run the native:queue command manually, it throws an error: php is a directory.

Btw, how do you make the queue command auto run like scheduler? I saw in the source code that had an env variable to skip the queue. I tried to set it to false but nothing happened.

**Comment by Jonnx** [comment]
seeing the same error message on a fresh project on mac osx

```
php artisan native:queue
Starting NativePHP queue worker…
sh: /Users/jonasweigert/Development/Personal/com.cachely.app/vendor/nativephp/electron/src/Commands/../../resources/js/resources/php: is a directory
```

**Comment by mpociot** [comment]
Ah you're right, this was introduced with Windows support. Thanks!

**Comment by Jonnx** [comment]
php artisan native:queue now works with the latest changes and processes queue successfully

**Pull request merged**
